"""add task assignee

Revision ID: 612525d8a64e
Revises: db9b84675e52
Create Date: 2026-07-07 23:51:08.075044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '612525d8a64e'
down_revision: Union[str, Sequence[str], None] = 'db9b84675e52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('assigned_to_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'users', ['assigned_to_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'assigned_to_user_id')
    # ### end Alembic commands ###
