"""add task approval details

Revision ID: ca6c154d50ea
Revises: 61c98480469e
Create Date: 2026-07-09 22:24:39.500057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca6c154d50ea'
down_revision: Union[str, Sequence[str], None] = '61c98480469e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('approved_by_user_id', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('revision_requested_by_user_id', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('approved_at', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('revision_requested_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'users', ['approved_by_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'tasks', 'users', ['revision_requested_by_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'revision_requested_at')
    op.drop_column('tasks', 'approved_at')
    op.drop_column('tasks', 'revision_requested_by_user_id')
    op.drop_column('tasks', 'approved_by_user_id')
    # ### end Alembic commands ###
