from enum import Enum


class AuditAction(str, Enum):
    ORGANIZATION_CREATED = "ORGANIZATION_CREATED"
    ORGANIZATION_MEMBER_ADDED = "ORGANIZATION_MEMBER_ADDED"

    PROJECT_CREATED = "PROJECT_CREATED"
    PROJECT_MEMBER_ADDED = "PROJECT_MEMBER_ADDED"

    TASK_CREATED = "TASK_CREATED"
    TASK_UPDATED = "TASK_UPDATED"
    TASK_ASSIGNED = "TASK_ASSIGNED"
    TASK_STATUS_CHANGED = "TASK_STATUS_CHANGED"

    COMMENT_CREATED = "COMMENT_CREATED"